@extends('layouts.app')

@section('title', trans('account.account') . ': ' . trans('account.2fa.name'))

@section('content')

    <div class="container">
        @include('account.parts.navigation')
        <br>
        <br>
        <div class="panel panel-default">
            <div class="panel-heading">@yield('title')</div>

            <div class="panel-body">
                <ol>
                    <li>
                        Download the <a href="https://support.google.com/accounts/answer/1066447">Google Authenticator app</a> on your phone.
                    </li>
                    <li>
                        Scan the QR code with Google Authenticator
                        <img src="{{ $google2fa_url }}" class="img-responsive">
                    </li>
                    <li>
                        To confirm everything works, enter the key generated by the app down below and click "Verify".
                    </li>
                </ol>
                {!! Form::open(['route' => 'account.2fa.verify']) !!}
                <div class="form-group{{ $errors->has('key') ? ' has-error' : '' }}">
                    {!! Form::label('key', trans('forms.key'), ['class' => 'control-label']) !!}
                    {!! Form::text('key', null, ['class' => 'form-control input-lg', 'placeholder' => '120124', 'autofocus']) !!}
                    @if ($errors->has('key'))
                        <span class="help-block">
                            <strong>{{ $errors->first('key') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">{{ trans('forms.verify') }}</button>
                    <a href="{{ route('account.2fa.disable') }}" class="btn btn-danger">{{ trans('forms.cancel') }}</a>
                </div>

            </div>
        </div>
    </div>

@endsection
